/**
 * BANG frontend config.
 * This is the dev-time fallback — production deploys read
 * config_fe_bang.json generated by the math SDK's run.py.
 * Keep symbol IDs + dimensions in sync with games/bang/game_config.py.
 */
export default {
	providerName: 'CrossFireGaming',
	gameName: 'BANG',
	gameID: 'bang',
	rtp: 0.977,
	numReels: 5,
	numRows: [5, 5, 5, 5, 5],
	betModes: {
		base: {
			cost: 1.0,
			feature: true,
			buyBonus: false,
			rtp: 0.977,
			max_win: 50000.0,
		},
		feature: {
			cost: 20.0,
			feature: true,
			buyBonus: false,
			rtp: 0.977,
			max_win: 50000.0,
		},
	},
	// BANG symbol set. DS / DB are wilds (substitute for any cluster
	// symbol) AND detonate their area-effect when in a winning cluster.
	// Paytable is tiered: 4-5 / 6-7 / 8-11 / 12-15 / 16-19 / 20-25.
	symbols: {
		// High pays
		H1: {
			// Safe / Vault — top pay
			paytable: [
				{ '4': 1.43 }, { '5': 1.43 },
				{ '6': 3.43 }, { '7': 3.43 },
				{ '8': 8.6 }, { '9': 8.6 }, { '10': 8.6 }, { '11': 8.6 },
				{ '12': 22.92 }, { '13': 22.92 }, { '14': 22.92 }, { '15': 22.92 },
				{ '16': 71.6 }, { '17': 71.6 }, { '18': 71.6 }, { '19': 71.6 },
				{ '20': 286.42 }, { '21': 286.42 }, { '22': 286.42 },
				{ '23': 286.42 }, { '24': 286.42 }, { '25': 286.42 },
			],
			special_properties: [],
		},
		H2: {
			// Gold Bar
			paytable: [
				{ '4': 1.0 }, { '5': 1.0 },
				{ '6': 2.15 }, { '7': 2.15 },
				{ '8': 5.15 }, { '9': 5.15 }, { '10': 5.15 }, { '11': 5.15 },
				{ '12': 14.32 }, { '13': 14.32 }, { '14': 14.32 }, { '15': 14.32 },
				{ '16': 37.24 }, { '17': 37.24 }, { '18': 37.24 }, { '19': 37.24 },
				{ '20': 171.85 }, { '21': 171.85 }, { '22': 171.85 },
				{ '23': 171.85 }, { '24': 171.85 }, { '25': 171.85 },
			],
			special_properties: [],
		},
		H3: {
			// Sheriff Badge
			paytable: [
				{ '4': 0.57 }, { '5': 0.57 },
				{ '6': 1.43 }, { '7': 1.43 },
				{ '8': 3.43 }, { '9': 3.43 }, { '10': 3.43 }, { '11': 3.43 },
				{ '12': 8.6 }, { '13': 8.6 }, { '14': 8.6 }, { '15': 8.6 },
				{ '16': 22.92 }, { '17': 22.92 }, { '18': 22.92 }, { '19': 22.92 },
				{ '20': 85.92 }, { '21': 85.92 }, { '22': 85.92 },
				{ '23': 85.92 }, { '24': 85.92 }, { '25': 85.92 },
			],
			special_properties: [],
		},
		H4: {
			// Horseshoe
			paytable: [
				{ '4': 0.4 }, { '5': 0.4 },
				{ '6': 1.0 }, { '7': 1.0 },
				{ '8': 2.29 }, { '9': 2.29 }, { '10': 2.29 }, { '11': 2.29 },
				{ '12': 5.15 }, { '13': 5.15 }, { '14': 5.15 }, { '15': 5.15 },
				{ '16': 14.32 }, { '17': 14.32 }, { '18': 14.32 }, { '19': 14.32 },
				{ '20': 51.56 }, { '21': 51.56 }, { '22': 51.56 },
				{ '23': 51.56 }, { '24': 51.56 }, { '25': 51.56 },
			],
			special_properties: [],
		},
		// Low pays
		L1: {
			// Diamond
			paytable: [
				{ '4': 0.2 }, { '5': 0.2 },
				{ '6': 0.43 }, { '7': 0.43 },
				{ '8': 1.0 }, { '9': 1.0 }, { '10': 1.0 }, { '11': 1.0 },
				{ '12': 2.29 }, { '13': 2.29 }, { '14': 2.29 }, { '15': 2.29 },
				{ '16': 5.73 }, { '17': 5.73 }, { '18': 5.73 }, { '19': 5.73 },
				{ '20': 20.05 }, { '21': 20.05 }, { '22': 20.05 },
				{ '23': 20.05 }, { '24': 20.05 }, { '25': 20.05 },
			],
			special_properties: [],
		},
		L2: {
			// Heart
			paytable: [
				{ '4': 0.2 }, { '5': 0.2 },
				{ '6': 0.43 }, { '7': 0.43 },
				{ '8': 1.0 }, { '9': 1.0 }, { '10': 1.0 }, { '11': 1.0 },
				{ '12': 2.29 }, { '13': 2.29 }, { '14': 2.29 }, { '15': 2.29 },
				{ '16': 5.73 }, { '17': 5.73 }, { '18': 5.73 }, { '19': 5.73 },
				{ '20': 20.05 }, { '21': 20.05 }, { '22': 20.05 },
				{ '23': 20.05 }, { '24': 20.05 }, { '25': 20.05 },
			],
			special_properties: [],
		},
		L3: {
			// Club
			paytable: [
				{ '4': 0.23 }, { '5': 0.23 },
				{ '6': 0.52 }, { '7': 0.52 },
				{ '8': 1.29 }, { '9': 1.29 }, { '10': 1.29 }, { '11': 1.29 },
				{ '12': 3.43 }, { '13': 3.43 }, { '14': 3.43 }, { '15': 3.43 },
				{ '16': 8.6 }, { '17': 8.6 }, { '18': 8.6 }, { '19': 8.6 },
				{ '20': 31.5 }, { '21': 31.5 }, { '22': 31.5 },
				{ '23': 31.5 }, { '24': 31.5 }, { '25': 31.5 },
			],
			special_properties: [],
		},
		L4: {
			// Spade
			paytable: [
				{ '4': 0.23 }, { '5': 0.23 },
				{ '6': 0.52 }, { '7': 0.52 },
				{ '8': 1.29 }, { '9': 1.29 }, { '10': 1.29 }, { '11': 1.29 },
				{ '12': 3.43 }, { '13': 3.43 }, { '14': 3.43 }, { '15': 3.43 },
				{ '16': 8.6 }, { '17': 8.6 }, { '18': 8.6 }, { '19': 8.6 },
				{ '20': 31.5 }, { '21': 31.5 }, { '22': 31.5 },
				{ '23': 31.5 }, { '24': 31.5 }, { '25': 31.5 },
			],
			special_properties: [],
		},
		// Specials (wild + area-effect destruction)
		DS: {
			// Small Dynamite — wild, destroys row + column on cluster hit
			paytable: null,
			special_properties: ['wild'],
		},
		DB: {
			// Big Dynamite — wild, destroys 3x3 area on cluster hit
			paytable: null,
			special_properties: ['wild'],
		},
	},
	// Padding reel-strip symbols (one above + one below the visible
	// 5×5 board for tumble animations). One per reel; values are
	// arbitrary placeholders.
	paddingReels: {
		basegame: [
			[{ name: 'L1' }, { name: 'L2' }],
			[{ name: 'L1' }, { name: 'L3' }],
			[{ name: 'L2' }, { name: 'H4' }],
			[{ name: 'L4' }, { name: 'H4' }],
			[{ name: 'L3' }, { name: 'L2' }],
		],
		freegame: [
			[{ name: 'L1' }, { name: 'DS' }],
			[{ name: 'L2' }, { name: 'H4' }],
			[{ name: 'L3' }, { name: 'DS' }],
			[{ name: 'L4' }, { name: 'H3' }],
			[{ name: 'L1' }, { name: 'DB' }],
		],
	},
};
